### ISSUE TITLE
[BE] Fix: 240613 수정 목록

### ISSUE THREAD

**Issue by KangJeongHo1** [OZ-Coding-School/oz_02_main-003-BE#108]
### ✅ To-Do
- [x] 유저 이미지 업로드 및 삭제
- [x] 유저 메인페이지 메인 이미지 가져오기
- [x] 레시피 생성시 재료 저장
- [x] step - 버튼 눌렀을 때 order 데이터와 같은 order가 DB에 있는지 확인 
- [x] (있을시 order = 삭제된 스텝의 오더보다  큰 order 를 -1하고 저장) + 삭제된 스텝에 대한 데이터를 DB에서 날리기
