### ISSUE TITLE
[BE] Feat: user API 개발 

### ISSUE THREAD

**Issue by newbission** [OZ-Coding-School/oz_02_main-003-BE#61]
### ⚠️ ISSUE
유저 데이터에서 필요한 정보를 최초 한 번 입력 받기

### ✅ To-Do
- [x] 알림 여부 관리 (put)
- [x] 사용자 정보 디테일 입력 (post)
- [x] 사용자 정보 수정 (put)
- [x] 사용자 계정 탈퇴 (delete)
- [x] 사용자 계정 조회 (get)
