### ISSUE TITLE
[BE] Feat: 레시피 관련 API 관련 수정

### ISSUE THREAD

**Issue by KangJeongHo1** [OZ-Coding-School/oz_02_main-003-BE#81]
### ✅ To-Do
- [x] 특정 레시피 조회 기능 수정
- [x] 카테고리별 레시피 조회 기능 수정
- [ ] 검색어로 레시피 조회 기능 수정
