### ISSUE TITLE
[BE] Feat: 유저 이미지 생성 API 기능 개발

### ISSUE THREAD

**Issue by KangJeongHo1** [OZ-Coding-School/oz_02_main-003-BE#90]
### ✅ To-Do
- [x] 유저 데이터 가져오기
- [x] 유저 이미지 생성
- [x] 유저 이미지 수정
